### ISSUE TITLE
acyscales Sodium gui option not showing up

### ISSUE THREAD

**Issue by vanvac** [pog5/anyscale#2]
Idk what is causing it but the option for the scale menu just dosen't load and when i search for the options using reeces sodium options it also didnt show 

I did however find this in the log file 
[15:37:39] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI was not found anyscale.mixins.json:client.SodiumOptionsGUIMixin from mod anyscale

i do have sodium extra, xaero plus and more culling which add extra sodium tabs but removing them didnt seem to fix the problem

**Comment by vanvac** [comment]
if you need any other information about the minecraft instance or the log file please do ask i will provide as i see this mod as very cool and can be useful for some stuff

**Comment by pog5** [comment]
thank you for making a issue :)
can you send your log on https://mclo.gs
also your minecraft, sodium and anyscale versions
thank you!

**Comment by vanvac** [comment]
[latest.log](https://github.com/user-attachments/files/17103501/latest.log)
https://mclo.gs/t4SszHs
i did it on the site you gave but here is the file just in case i messed something up there 
minecraft version > 1.21.1
os information 
![image](https://github.com/user-attachments/assets/af3aea98-878c-4eaa-840d-fdadb38f1508)

sodium-Fabric 0.6.0-beta2 
sodium-Extra 0.6.0-beta3
reese's-sodium-options 1.8.0-beta4

These versions of mods were what prismlaunchers auto update mods thing installed i didnt manuslly install these

**Comment by vanvac** [comment]
minecraft launches completely fine it dosen't cause a crash(if it wssn't obvious)

**Comment by pog5** [comment]
support for minecraft 1.20.5 and higher is VERY experimental because mojang changed a big part of how the game works overall, including screens, the versions for it are marked as alpha for a reason. i'll try to release 1.21 version soon

**Comment by pog5** [comment]
for now you can try editing the config file manually (`.minecraft/config/anyscale.json`)

**Comment by vanvac** [comment]
ok good to know ty

**Comment by vanvac** [comment]
i went into the config folder and was unable to find the config file for the mod any way you could give me like the backbone structure of it so i can coustomise it

**Comment by pog5** [comment]
What do you mean by "the backbone structure of it"? If you mean the source code, it's open source, you're free to see and modify the code under the license provided.

**Comment by vanvac** [comment]
dw i just installed the 1.20.5 version of it and copied the json file form there
